# Generated by Django 4.1.5 on 2023-03-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table1',
            name='deathyear',
            field=models.IntegerField(null=True),
        ),
    ]
