# Generated by Django 4.1.5 on 2023-03-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_table1_deathyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='table1',
            name='joined_date',
            field=models.DateField(null=True),
        ),
    ]
